"""Render permissions.json into permissions.md + Claude Code deny patterns.

Single source of truth is `protocols/permissions.json`. This script writes:

  1. `protocols/permissions.md` — human-readable rendering for agent context.
  2. `protocols/.claude-deny.json` — just the Bash deny patterns, for adapter
     installers to merge into `.claude/settings.json`.

Run locally after editing permissions.json. CI (tools/9 — workflows) fails the
build if the rendered artifacts drift from the source.
"""
import os, sys, json, argparse

BASE = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
SRC = os.path.join(BASE, "protocols", "permissions.json")
MD = os.path.join(BASE, "protocols", "permissions.md")
DENY = os.path.join(BASE, "protocols", ".claude-deny.json")


_HEADER = """# Permissions

> **Generated from `permissions.json` by `tools/permissions_render.py`.**
> Do not edit this file directly. Edit `permissions.json` and regenerate.

The pre_tool_call hook reads `permissions.json` and enforces it before any
tool invocation. Humans edit the source; the agent does not.

"""


def render_md(policy):
    lines = [_HEADER]
    lines.append("## Always allowed (no approval)\n")
    for item in policy.get("always_allowed", []):
        lines.append(f"- {item}")
    lines.append("\n## Requires approval\n")
    for item in policy.get("requires_approval", []):
        lines.append(f"- {item}")
    lines.append("\n## Never allowed\n")
    for block in policy.get("never_allowed", []):
        if isinstance(block, str):
            # Legacy plain-string rule — keep rendering it so older configs
            # upgrade gracefully without losing content during migration.
            lines.append(f"- {block}")
            continue
        lines.append(f"- {block['rule']}")
    lines.append("\n## Approved external domains\n")
    for d in policy.get("approved_domains", []):
        lines.append(f"- `{d}`")
    lines.append("")
    return "\n".join(lines)


def render_deny_patterns(policy):
    """Flatten the explicit Bash deny patterns across all never_allowed blocks.

    Adapter installers render this into `.claude/settings.json` so the
    Claude Code permission system enforces the same rules the pre_tool_call
    hook does, even when the hook isn't wired up (e.g., during first-run).
    """
    patterns = []
    for block in policy.get("never_allowed", []):
        if isinstance(block, dict):
            patterns.extend(block.get("patterns", []))
    # De-dupe while preserving order so diffs stay stable across runs
    seen, out = set(), []
    for p in patterns:
        if p not in seen:
            seen.add(p)
            out.append(p)
    return out


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="Exit non-zero if rendered artifacts differ from "
                         "what this script would write (for CI drift guard).")
    args = ap.parse_args(argv)

    if not os.path.exists(SRC):
        print(f"error: source not found: {SRC}", file=sys.stderr)
        sys.exit(1)
    with open(SRC) as f:
        policy = json.load(f)

    md = render_md(policy)
    deny = render_deny_patterns(policy)
    deny_json = json.dumps({"deny": deny}, indent=2) + "\n"

    if args.check:
        drift = []
        if os.path.exists(MD):
            with open(MD) as f:
                if f.read() != md:
                    drift.append(MD)
        else:
            drift.append(MD)
        if os.path.exists(DENY):
            with open(DENY) as f:
                if f.read() != deny_json:
                    drift.append(DENY)
        else:
            drift.append(DENY)
        if drift:
            print("DRIFT detected in:", file=sys.stderr)
            for p in drift:
                print(f"  - {p}", file=sys.stderr)
            print("run `python .agent/tools/permissions_render.py` locally "
                  "and commit the regenerated files.", file=sys.stderr)
            sys.exit(2)
        print("permissions artifacts in sync with source.")
        return

    with open(MD, "w") as f:
        f.write(md)
    with open(DENY, "w") as f:
        f.write(deny_json)
    print(f"wrote {MD}")
    print(f"wrote {DENY}")


if __name__ == "__main__":
    main()
